service: deepthought
runtime: nodejs22

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always

  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

# Standard environment configuration for cost savings
instance_class: F1  # Smallest instance class
automatic_scaling:
  min_idle_instances: 0  # Scale to zero when not in use
  max_idle_instances: 1  # Limit idle instances
  min_pending_latency: 3000ms  # Longer latency before scaling up
  max_pending_latency: 6000ms
  max_instances: 1  # Limit maximum instances
